server.port=8081

logging.level.root=INFO
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10

# Gateway service-to-service config
gateway.url=${GATEWAY_URL:http://localhost:8080}
gateway.servicekey=${GATEWAY_SERVICEKEY:dev-service-key}